### ISSUE TITLE
tar: *.vmx: Not found in archive

### ISSUE THREAD

**Issue by svanschalkwyk** [mechboxes/mech#37]
Mech output:
$mech up
Loading metadata for box 'bento/ubuntu-16.04' (201806.08.0)
Box 'bento/ubuntu-16.04' could not be found. Attempting to download...
URL: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/201806.08.0/providers/vmware_desktop.box
vmware_desktop.box [################################] 479786/479786 - 00:03:58
Checking box 'bento/ubuntu-16.04' integrity...
/tmp/tmpsBYBh_
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: *.vmx: Not found in archive
tar: Exiting with failure status due to previous errors
Bringing machine up...
ERROR: Error: Cannot open VM: /home/steph/Projects/mech/nogui, unknown file suffix
VM not started

Tar version: 
tar --version
tar (GNU tar) 1.28

tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: *.vmx: Not found in archive
tar: Exiting with failure status due to previous errors
Bringing machine up...
Traceback (most recent call last):
  File "/usr/local/bin/mech", line 11, in <module>
    load_entry_point('mech==0.6.0', 'console_scripts', 'mech')()
  File "build/bdist.linux-x86_64/egg/mech/__main__.py", line 39, in main
  File "build/bdist.linux-x86_64/egg/mech/command.py", line 71, in __call__
  File "build/bdist.linux-x86_64/egg/mech/mech.py", line 606, in up
  File "build/bdist.linux-x86_64/egg/mech/vmrun.py", line 144, in start
  File "build/bdist.linux-x86_64/egg/mech/vmrun.py", line 105, in vmrun
  File "build/bdist.linux-x86_64/egg/mech/vmrun.py", line 105, in <genexpr>
TypeError: argument of type 'NoneType' is not iterable

vmware-vixWrapper-9322.log contents:
2018-06-26T13:04:28.981-05:00| vthread-4| I125: Log for VixWrapper pid=9322 version=1 build=build-7535481 option=Release
2018-06-26T13:04:28.981-05:00| vthread-4| I125: The process is 64-bit.
2018-06-26T13:04:28.981-05:00| vthread-4| I125: Host codepage=UTF-8 encoding=UTF-8
2018-06-26T13:04:28.981-05:00| vthread-4| I125: Host is Linux 4.4.0-62-generic Linux Mint 18 Sarah
2018-06-26T13:04:28.980-05:00| vthread-4| I125: DictionaryLoad: Cannot open file "/usr/lib/vmware/settings": No such file or directory.
2018-06-26T13:04:28.980-05:00| vthread-4| I125: PREF Optional preferences file not found at /usr/lib/vmware/settings. Using default values.
2018-06-26T13:04:28.980-05:00| vthread-4| I125: DictionaryLoad: Cannot open file "/home/steph/.vmware/config": No such file or directory.
2018-06-26T13:04:28.980-05:00| vthread-4| I125: PREF Optional preferences file not found at /home/steph/.vmware/config. Using default values.
2018-06-26T13:04:29.039-05:00| vthread-4| I125: Workstation installed version is 12.5.9
2018-06-26T13:04:29.039-05:00| vthread-4| I125: Loading Vix implementation library /usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so
2018-06-26T13:04:29.041-05:00| vthread-4| I125: unable to load func Vix_PumpEvents from library /usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so (/usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so: undefined symbol: Vix_PumpEvents)
2018-06-26T13:04:29.041-05:00| vthread-4| I125: unable to load func VixVM_OpenUrlInGuest from library /usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so (/usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so: undefined symbol: VixVM_OpenUrlInGuest)
2018-06-26T13:04:29.041-05:00| vthread-4| I125: unable to load func VixVM_VProbeLoad from library /usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so (/usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so: undefined symbol: VixVM_VProbeLoad)
2018-06-26T13:04:29.041-05:00| vthread-4| I125: unable to load func VixVM_GetVProbes from library /usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so (/usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so: undefined symbol: VixVM_GetVProbes)
2018-06-26T13:04:29.041-05:00| vthread-4| I125: unable to load func VixVM_VProbeGetGlobalVars from library /usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so (/usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so: undefined symbol: VixVM_VProbeGetGlobalVars)
2018-06-26T13:04:29.041-05:00| vthread-4| I125: unable to load func VixVM_VProbeReset from library /usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so (/usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so: undefined symbol: VixVM_VProbeReset)
2018-06-26T13:04:29.041-05:00| vthread-4| I125: unable to load func VixVM_GetVProbesVersion from library /usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so (/usr/lib/vmware-vix/Workstation-12.0.0/64bit/libvix.so: undefined symbol: VixVM_GetVProbesVersion)
2018-06-26T13:04:29.294-05:00| vthread-4| I125: DictionaryLoad: Cannot open file "/home/steph/vmware/Me-lw/nogui": No such file or directory.

**Comment by Kronuz** [comment]
This is a dup of #35. Should be fixed in v0.7.6.

**Comment by svanschalkwyk** [comment]
Thanks, but still occurs:
`
steph@swartjie ~/Projects/manifoldcf/mech/test $ mech up
Loading metadata for box 'bento/ubuntu-16.04' (201806.08.0)
Box 'bento/ubuntu-16.04' could not be found. Attempting to download...
URL:
https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/201806.08.0/providers/vmware_desktop.box
vmware_desktop.box [################################] 479786/479786 -
00:04:21
Checking box 'bento/ubuntu-16.04' integrity...
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to
suppress this warning
tar: *.vmx: Not found in archive
tar: Exiting with failure status due to previous errors
Cannot find a valid box with a VMX file in it
steph@swartjie ~/Projects/manifoldcf/mech/test $ mech --version
mech v0.7.6
'



*Steph van Schalkwyk*
Principal, Remcam Search Engines
+1.314.452. <+1+314+452+2896>2896    steph@remcam.net   http://remcam.net
<http://www.remcam.net/> Skype: svanschalkwyk
<https://mail.google.com/mail/u/0/#>
<http://linkedin.com/in/vanschalkwyk>

**Comment by hth2** [comment]
I have the same issue with mech v0.7.6:

```
$ mech init bento/debian-9.5
Initializing mech
Loading metadata for box 'bento/debian-9.5'
A `Mechfile` has been initialized and placed in this directory. You
are now ready to `mech up` your first virtual environment!

$ mech up
Loading metadata for box 'bento/debian-9.5' (201808.24.0)
Box 'bento/debian-9.5' could not be found. Attempting to download...
URL: https://vagrantcloud.com/bento/boxes/debian-9.5/versions/201808.24.0/providers/vmware_desktop.box
vmware_desktop.box [################################] 469925/469925 - 00:03:01
Checking box 'bento/debian-9.5' integrity...
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: *.vmx: Not found in archive
tar: Exiting with failure status due to previous errors
Cannot find a valid box with a VMX file in it

$ mech -v
mech v0.7.6

$ where tar
/bin/tar

$ tar --version 
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.

$ uname -a
Linux pc 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

```
